### ISSUE TITLE
Improve Structured Data

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#14]
Test and improve structured data on the site. Here's a sample page run through the [Google Structured Data Testing tool](https://developers.google.com/structured-data/testing-tool?url=http%253A%252F%252Fwww.nhdnug.org%252Fmeetings%252F2016%252F04%252F21%252FJavascript-Testing).

Second, individual meetings should have accurate twitter cards (currently only a summary card is generated).

Third, the canonical URL currently shows the github.io address instead of the fully qualified.

**Comment by jmreynolds** [comment]
What is a "Twitter Card"?

**Comment by jmreynolds** [comment]
Should items 2 and 3 be separate issues?

**Comment by jonthenerd** [comment]
I dont believe so. They're all structured data related, so I plan to fix all I can within this branch.

Jon

**Comment by jmreynolds** [comment]
Oops! Hit the wrong button.
Should be assigned to @jonthenerd, and categorized as Data now.
