### ISSUE TITLE
Sponsor Logos and Descriptions

### ISSUE THREAD

**Issue by jmreynolds** [NHDNUG/nhdnug.github.io#2]
There needs to be a style layout for sponsors. Particularly our Platinum Sponsor (Improving) - I'd like to get this in as a high-priority thing. Unfortunately, it goes beyond my skill set.

**Comment by jmreynolds** [comment]
@jonthenerd is this something you could do you think?

**Comment by jonthenerd** [comment]
#3 addresses this, and a little more.
