### ISSUE TITLE
Move sessions from old site to new site

### ISSUE THREAD

**Issue by jmreynolds** [NHDNUG/nhdnug.github.io#21]
I had started this before, but with all the changes @jonthenerd has made, I want to review the Python script and make sure it seems like it's still on track to bring everything in correctly. Also, I think this is probably predicated on having the speakers brought in correctly first.

**Comment by jmreynolds** [comment]
Related to #34 - This issue is strictly related to content though, not link structure.

**Comment by jonthenerd** [comment]
Note - #34 references that once we migrate old content, there are presenters who may wish to get new URLs to their meeting topics. We should consider emailing these folks the details, or at least a "hey check out our new site and get your URLs if you want them" kind of email.

**Comment by jmreynolds** [comment]
Yeah - that would probably be a good idea - at least the ones for whom I have a valid email.
I'm almost done importing the old stuff into _drafts. I'll push it up for you to review, then we can bring it over into the _posts folder.

**Comment by jmreynolds** [comment]
Should be fixed by 1fd022d - but needs to be reviewed.

**Comment by jonthenerd** [comment]
Merging dev into master #39

**Comment by jonthenerd** [comment]
We can either leave this open until more meetings are pulled in, or go ahead and close. Your call Joe.

**Comment by jmreynolds** [comment]
Waiting to move the remainder of the drafts into posts until the speaker\s issue is resolved. #37
