### ISSUE TITLE
Thoughts on Tagging and releases...

### ISSUE THREAD

**Issue by jmreynolds** [NHDNUG/nhdnug.github.io#33]
So @jonthenerd and I were discussing the tag and release schedule for the NHDNUG site, and I've been doing some thinking about it since then... I don't know that we _really_ need to tag every push to master - mostly because most of them are going to be "I updated John Doe's bio" or "I added a new session".

That said - I'm thinking that around the 1st of the month, we should probably tag what we have, just so if something goes completely sideways, we can always get back to it.

I'm very curious what y'all think, and would love to hear from people who do this (open source, and Git workflow management) more than I do... @justinSelf? @gregmajor? @dgwaldo? (Yeah I know y'all aren't officially part of the group, but you've spoken or _been_ part of the group, so you get to weigh in if you'd like!)

Thanks for the input!

**Comment by jonthenerd** [comment]
Personally, I think we could revert back to a specific commit... releases feel more like something you make available for download and that's not really useful with a website. Just my thoughts, but I'm the least experienced with git by far.

**Comment by jmreynolds** [comment]
My thought with Tags is they're easier to find than commits - there's less noise. I generate dozens of commits per day at times - versus one tag per month, unless there's a major overhaul. Might be a little easier to keep track of. But again - I don't have a whole lot of energy on this - just something I think we need to think about.

**Comment by jonthenerd** [comment]
Part of the issue with doing releases for this is that we have "code" (kinda maybe if you consider this stuff code) and content changes. I can clearly see value in marking releases for when the templates, data structure, etc. change, and not for content changes. However, we could very well go a long time between code changes once this stabilizes and you'd lose your easy revert option and have to hunt a commit (which you don't want). Eh. Mixed bag. 

Let's keep up what we're doing (doing a release each time we merge to master) for a while and see if it's too tedious.

Also - is doing a pull request from dev to master to get the changes the right thing to do? Is there another way to do this, or is it the normal way of things?

**Comment by dgwaldo** [comment]
Hi All,

I miss the meetups down there, you have a passionate group!  I'll interject
my two cents.  Currently we have a default branch which we do feature
branches off of, and then we make a release branch from default for every
release and pull any additional things from the feature branches onto it
and clean it up, and merge it back into default.

This can be a tedious and error prone process, but we let the team lead
take care of it, its his nightmare :)  The better part of our process is
the code review process that takes place when merging anything from a
feature branch back into default.  We are doing unit tests for all our code
now, and with code review on every merge it's really helped keep the code
base clean.

On a side note we've been refactoring our entire product to get closer to
continuous delivery.  Our company is fairly concerned about web performance
and scalability.  I've found that we tend to look to processes used by
StackOverflow as our guide, for example we now use Dapper as our ORM.   The
following article on their deployment process is pretty interesting.  They
heavily use master, with sparing use of feature branches...

http://nickcraver.com/blog/2016/05/03/stack-overflow-how-we-do-deployment-2016-edition/

Take care,

Don W.

**Comment by jmreynolds** [comment]
> we make a release branch from default for every
release ... and merge it back into default.

I find it interesting that you aren't merging from `Dev` up to `Master` - to help keep the release line more clean. Most projects I work on, we find it fairly pain free to have `Master` as our "Source of Truth", `Dev` is the "Stable, but in flux" branch, and `Feature` branches are the "use at your own risk" branches.
* We do pull requests from `Feature` to `Dev`, the team lead and someone else reviews and approves, and the original author is in charge of integrating it into `Dev`.
* Then at some schedule, `Dev` is released into `Master` via a `Release` branch (mainly to support a tag structure). 

Essentially, we follow the standard GitFlow workflow.

The Dapper\SO workflow is interesting - but as they said, I don't know that it would work in every case. I tend to be protective of `Master` - but I've seen weird stuff checked in and break builds. I was working with a developer one time who was like "Oh, there was a conflict, so I deleted that file. It didn't look important." As I recall, it was a web.config or something equally useful.

**Comment by jmreynolds** [comment]
>  Let's keep up what we're doing (doing a release each time we merge to
 master) for a while and see if it's too tedious.

Sounds good. I'll close the issue and we can re-open if necessary.

> Also - is doing a pull request from dev to master to get the changes the right thing to do? Is there another way to do this, or is it the normal way of things?

No - if the issue is closed out and Develop has been integrated with a feature, you or I can create a release branch at any point and push that into Master. No Pull Request needed.
