### ISSUE TITLE
Previous speeches and topic records

### ISSUE THREAD

**Issue by ArunSajjan** [NHDNUG/nhdnug.github.io#34]
I believe, we need to maintain the previous speech and topic records in the new web-site. In my personal website http://www.booklet.co , I referred my speeches/topics links to the old website links. And currently they are broken. If you can update history records in the new website that will be great for later references and learning. My presentations are also available for download. If possible, you can keep them as downloadable presentations on history page of nhdnug.org

**Comment by jmreynolds** [comment]
@ArunSajjan - We are definitely aware of this issue and working to make sure the best approach is taken to make sure the old material is imported back in to the new site. Out of curiosity, how much of an inconvenience would it be if instead of the old format: "/Meetings/Details/93" we used the new format: "meetings/2016/05/19/NServiceBus"?

Thanks for your feedback!

**Comment by ArunSajjan** [comment]
Thank for your reply and thank you for your services to tech community. I can comply with requirements and update new links in matter of couple of minutes.

Thank you.

Arun

Sent from Outlook Mobile






On Tue, May 3, 2016 at 7:43 AM -0700, "Joe Reynolds" <notifications@github.com> wrote:





@ArunSajjan - We are definitely aware of this issue and working to make sure the best approach is taken to make sure the old material is imported back in to the new site. Out of curiosity, how much of an inconvenience would it be if instead of the old format: "/Meetings/Details/93" we used the new format: "meetings/2016/05/19/NServiceBus"?

Thanks for your feedback!

---

**Comment by jmreynolds** [comment]
Ok - we'll take a look at the implications here. @jonthenerd you've don't a little more on this than I have at this point - I think there's a way to customize how the link structure works, but I think the year\month format is better in general than the "meetingnumber" format - do you disagree?

**Comment by jonthenerd** [comment]
I prefer the year/month formatting we have on the new site, as it does allow us additional flexibility to group and display meetings. Once we import the old meetings, we can provide new URLs to those who need them, and if pushed implement redirects for those unable to update sites they don't maintain and can't have updated.

**Comment by jonthenerd** [comment]
Also, since this data will be migrated as part of #21 , I'm closing this issue. Let's keep the discussion going (if needed) on that other issue so it's centralized there.
