### ISSUE TITLE
Need a data format for sessions with multiple speakers

### ISSUE THREAD

**Issue by jmreynolds** [NHDNUG/nhdnug.github.io#37]
As an example - [The SignalR Session](/NHDNUG/nhdnug.github.io/blob/1fd022d1a87af4734d2ac7c74bf252882f230308/_drafts/2013-05-16-SignlR.md) - This has two authors, Graham Swor and Michael Nero. I think there are others, but I'm not sure.

Any thoughts on this?

**Comment by jonthenerd** [comment]
Yeah. We should fix this before we pull in any mass number of meetings. I'd rather have one property for "speakers" instead of two and just retrofit the existing content.

**Comment by jmreynolds** [comment]
Ok - in that case I will close out issue #21 and once all the speaker tags have been reviewed, we can just move from _drafts to _posts.

**Comment by jmreynolds** [comment]
I'm thinking this will look similar to the sponsor\s tag - I'll take a look today.

**Comment by jmreynolds** [comment]
Ok - so I'm working on a feature branch - and I'm cleaning up `sponsor` vs `sponsors` - making them all plural. That way the `speaker` vs `speakers` is not such a big deal.

**Comment by jonthenerd** [comment]
Sounds good

Jon

**Comment by jonthenerd** [comment]
Done!
