### ISSUE TITLE
June 2016 Meeting Details

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#42]
We need additional information for the June 2016 Meeting:

- [x] John Cavnar-Johnson's Bio Pic (350px by 350px)
- [x] John Cavnar-Johnson's Bio Summary
- [x] Meeting summary

Created a branch for it. Looking for details on the web... Would love some help @jmreynolds .

**Comment by jonthenerd** [comment]
Found a 150x150 pic on the net, and pulled together some bio info from his LinkedIn and Twitter profiles. Still need a meeting summary.

**Comment by jmreynolds** [comment]
Just emailed John to get the latest info - I apparently don't have it.

**Comment by jonthenerd** [comment]
Thanks!

**Comment by jonthenerd** [comment]
Pull request #46 has these details now, as well as other improvements to the rest of the site.

**Comment by jonthenerd** [comment]
Found better details in my email. Getting those put in now.
