### ISSUE TITLE
Import Meeting History

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#45]
Multi-speaker and multi-sponsor are merged into master. Improved meeting history display is in develop (will show years of prior meeting where we have none there in master).

Here's what needs to get done to finish this out:
- [ ] Python script updated to properly output multi-speaker and multi-sponsor
- [ ] Historical meetings/speakers moved out of draft, then reviewed

@jmreynolds I think this is all yours, but let me know if you need anything. I'd be glad to review once the files are spit out of the python script again.

Jon

**Comment by jmreynolds** [comment]
Thanks! I'll get to work on this soon. This week maybe? Hopefully?

Python script should be pretty easy to update, and then it's basically just a matter of going through and proof reading them.

**Comment by jonthenerd** [comment]
I'll be happy to help proof read and correct.

Thanks!

**Comment by jmreynolds** [comment]
Ugh. I have been totally out of touch on this. I will work on this while I'm in the car to Tulsa Tech Fest a week from today. Should be a fun diversion.

**Comment by jonthenerd** [comment]
No coding while driving Joe ;)
