### ISSUE TITLE
Sponsors not showing up

### ISSUE THREAD

**Issue by jmreynolds** [NHDNUG/nhdnug.github.io#48]
Hey @jonthenerd I think the multi-sponsors thing isn't working quite right - none of the sponsors seem to be showing up anywhere in the site.

**Comment by jonthenerd** [comment]
They were working when I published it...

Jon

**Comment by jmreynolds** [comment]
Are you saying _I_ might have screwed up??? *ME*??? I've never heard something so ludicrous...

(you can't see those dozen or so commits where I was trying to get the session published, and forgot that github doesn't like capital letters, can you???) 

I mean... yeah... hmm...

**Comment by jonthenerd** [comment]
Ha. Well. Serves me right for replying on my phone without looking at the commit history.

Jon
