### ISSUE TITLE
Add Ctuit as sponsor

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#50]

**Comment by jonthenerd** [comment]
Staged in a feature branch. Awaiting additional information from @jmreynolds

**Comment by jmreynolds** [comment]
@jonthenerd - I've got my VM Server up and running again, so I can finally look at these things. What information were you needing from me here?

**Comment by jonthenerd** [comment]
None as of now. We need to add Ctuit and Improving to the July meeting sponsors though. I should get to it later today.

Jon

**Comment by jmreynolds** [comment]
Ok - looked good to me, fwiw.

**Comment by jonthenerd** [comment]
Done.
