### ISSUE TITLE
Improve Sponsor Categorization and Display

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#51]
Need better categorization to allow differentiation and easier display of different sponsor levels.

**Comment by jmreynolds** [comment]
Anything you need from me on this?

**Comment by jonthenerd** [comment]
No. Just put the issue in to remind myself it needs working on.

Jon

**Comment by jonthenerd** [comment]
Put in pull request #52 (feature -> dev). I'd appreciate some feedback Joe. I think it's a great improvement to how to show sponsors on the site, but I'm probably biased.
