### ISSUE TITLE
August 2016 Meeting Details

### ISSUE THREAD

**Issue by jonthenerd** [NHDNUG/nhdnug.github.io#57]
Need info for 8/2016 meeting.

**Comment by jmreynolds** [comment]
Speaker: Greg Major
Topic: Review of Redgate SQL Server tools available for SQL Devs
Abstract: TBD - likely will focus on SQL Prompt, SQL Unit Tests, and SQL Data Generator
Meeting Sponsor: Redgate has given us a bundle of things to distribute. - lots of software, some tangibles, etc. No pizza\money\etc, but lots of free stuff.

Am I missing anything???

**Comment by jonthenerd** [comment]
Nope. Got it updated. Please update the Meetup to have the new room number.
